package com.greenicephoenix.traceledger.core.navigation

object Routes {
    const val ONBOARDING          = "onboarding"
    const val DASHBOARD           = "dashboard"
    const val ACCOUNTS            = "accounts"
    const val ADD_ACCOUNT         = "add_account"
    const val EDIT_ACCOUNT        = "add_account/{accountId}"
    const val TRANSACTIONS        = "transactions"
    const val ADD_TRANSACTION     = "add_transaction"
    const val EDIT_TRANSACTION    = "edit_transaction/{transactionId}"
    const val STATISTICS          = "statistics"
    const val STATISTICS_OVERVIEW = "statistics/overview"
    const val STATISTICS_BREAKDOWN = "statistics/breakdown"
    const val STATISTICS_INCOME   = "statistics/income"
    const val STATISTICS_CASHFLOW = "statistics/cashflow"
    const val STATISTICS_TRENDS   = "statistics/trends"
    const val SETTINGS            = "settings"
    const val CATEGORIES          = "categories"
    const val ADD_CATEGORY        = "add_category"
    const val EDIT_CATEGORY       = "edit_category/{categoryId}"
    const val BUDGETS             = "budgets"
    const val ADD_EDIT_BUDGET     = "add-edit-budget"
    const val ABOUT               = "about"
    const val RECURRING           = "recurring"
    const val ADD_RECURRING       = "add_recurring"
    const val EDIT_RECURRING      = "edit_recurring/{recurringId}"
}